In [0]:
import tensorflow  as tf

In [3]:
tf.__version__

'1.13.1'

In [0]:
hello=tf.constant("Hello")

In [0]:
world=tf.constant(" World")

In [6]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [7]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [0]:
with tf.Session() as sess:
 result= sess.run(hello+world)

In [9]:
result

'Hello World'

In [0]:
 a=tf.constant(10)
 b=tf.constant(20)

In [11]:
type(a)

tensorflow.python.framework.ops.Tensor

In [12]:
a+b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [13]:
a+b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [0]:
with tf.Session() as sess:
  result=sess.run(a+b)

In [15]:
result

30

In [0]:
const=tf.constant(10)

In [0]:
fill_mat=tf.fill((4,4,),10)

In [0]:
zeros=tf.zeros((4,4))

In [0]:
ones=tf.ones((3,3,))

In [0]:
randn=tf.random_normal((4,4),mean=2,stddev=1)

In [0]:
randu=tf.random_uniform((4,4),minval=1,maxval=2)

In [23]:
randn

<tf.Tensor 'random_normal:0' shape=(4, 4) dtype=float32>

In [0]:
operation_list=[const,fill_mat,zeros,ones,randn,randu]

In [0]:
#ALterate to with tf.Session() as sess:
sess=tf.InteractiveSession()

In [26]:
for op in operation_list:
  print(sess.run(op)) #or print(op.eval())
  print("\n")

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


[[4.4815598 3.135015  1.5196416 2.1847847]
 [2.7877748 4.813212  0.5609871 2.792186 ]
 [2.3697538 2.615354  0.5189066 0.9233329]
 [0.6481173 3.208583  1.0190153 2.8599076]]


[[1.680074  1.2366551 1.2491809 1.6460893]
 [1.160978  1.7881333 1.1425318 1.6475066]
 [1.4281188 1.4212778 1.6110727 1.2099905]
 [1.3681792 1.5444845 1.0850946 1.9452001]]




In [0]:
#Matrix Multiplication
a=tf.constant([[1,2,],[3,4,]])

In [30]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [0]:
 b=tf.constant([[100],[120]])

In [0]:
c=tf.matmul(a,b)

In [36]:
sess.run(c)

array([[340],
       [780]], dtype=int32)

In [37]:
c.eval()

array([[340],
       [780]], dtype=int32)